# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jukifyservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='display_name',
        ),
    ]
