# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukifyservice', '0004_auto_20171022_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_logged_at',
            field=models.DateTimeField(null=True),
        ),
    ]
