# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jukifyservice', '0005_auto_20171022_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='spotify_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='spotify_id',
            new_name='id',
        ),
    ]
