# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukifyservice', '0006_auto_20171022_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AddField(
            model_name='group',
            name='a',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
