# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukifyservice', '0009_auto_20171030_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='jukifyservice.PlaylistTrack', to='jukifyservice.Track'),
        ),
    ]
