# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukifyservice', '0010_playlist_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('track_id', models.CharField(max_length=256)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usagedata',
            unique_together=set([('user_id', 'track_id')]),
        ),
    ]
