# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukifyservice', '0011_auto_20171103_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
